name: layoutr
description: Succinct utilities to help doing responsive layouts with less verbosity
version: 1.0.0
repository: https://github.com/olmps/layoutr
issue_tracker: https://github.com/olmps/layoutr/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.0
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^0.0.2-dev
  strict: ^1.0.0
