name: granular_layout
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared:
    path: ../shared

  layoutr:
    path: ../../

dev_dependencies:
  strict: ^1.0.0-nullsafety

flutter:
  uses-material-design: true
